version: "3.9"
services:
  frontend:
    container_name: crypto-faucet-app
    image: crypto-faucet-app:1.0
    stdin_open: true
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - "/app/node_modules"
      - "./:/app"